module.exports = {
  someSidebar: {
    "Getting started": [
      "get-started",
      "configuration",
      "manual-triggers",
      "migrating-old-data",
      "understanding-data",
      "api",
    ],
    Integrations: [
      "integrations/intro",
      "integrations/spotify",
      "integrations/last-fm",
      "integrations/rescuetime",
      "integrations/wakatime",
      "integrations/pocket-casts",
      "integrations/goodreads",
      "integrations/twitter",
      "integrations/clockify",
      "integrations/google-fit",
      "integrations/oura-ring",
      "integrations/apple-health",
    ],
    Embed: ["embed/intro"],
    Action: ["action/intro"],
    Branding: ["branding/intro"],
    Policies: [
      "policies/intro",
      "policies/code-of-conduct",
      "policies/contributing",
      "policies/security",
      "policies/support",
    ],
  },
};
